# Generated by Django 2.1.2 on 2018-11-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
