# Generated by Django 2.1.2 on 2018-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('home', 'Home'), ('about', 'About')], default='home', max_length=5)),
                ('image', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('Mem', 'Member'), ('CSe', 'Secretary'), ('CTr', 'Treasurer'), ('CVP', 'Vice President'), ('CPr', 'President'), ('FSe', 'Former-Secretary'), ('FTr', 'Former-Treasurer'), ('FVP', 'Former-Vice President'), ('FPr', 'Former-President')], default='Mem', max_length=3)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('restriction', models.CharField(max_length=255)),
                ('deadline', models.DateField()),
                ('regrister', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
