# Generated by Django 2.1.2 on 2018-11-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0002_auto_20181116_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Member', 'Member'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer'), ('Vice President', 'Vice President'), ('President', 'President'), ('Former-Secretary', 'Former-Secretary'), ('Former-Treasurer', 'Former-Treasurer'), ('Former-Vice President', 'Former-Vice President'), ('Former-President', 'Former-President')], default='Member', max_length=25),
        ),
    ]
