# Generated by Django 2.1.2 on 2018-11-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs_app', '0003_auto_20181116_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='regrister',
            new_name='registrar',
        ),
    ]
